{% set name = "shakenbreak" %}
{% set pypi_version = "3.4.4" %}
{% set epoch = "1!" %}  # epoch 1 to try avoid issues with version scheme changes

package:
  name: {{ name|lower }}
  version: "{{ epoch }}{{ pypi_version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ pypi_version }}.tar.gz
  sha256: 4dce1352660cf067e7c2ce8de5c50c210ce875d5075cdaf880a8c129ef583e21

build:
  noarch: python
  number: 0
  entry_points:
    - snb = shakenbreak.cli:snb
    - snb-generate = shakenbreak.cli:generate
    - snb-generate_all = shakenbreak.cli:generate_all
    - snb-run = shakenbreak.cli:run
    - snb-parse = shakenbreak.cli:parse
    - snb-analyse = shakenbreak.cli:analyse
    - snb-plot = shakenbreak.cli:plot
    - snb-regenerate = shakenbreak.cli:regenerate
    - snb-groundstate = shakenbreak.cli:groundstate
    - snb-mag = shakenbreak.cli:mag
    - shakenbreak = shakenbreak.cli:snb
    - shakenbreak-generate = shakenbreak.cli:generate
    - shakenbreak-generate_all = shakenbreak.cli:generate_all
    - shakenbreak-run = shakenbreak.cli:run
    - shakenbreak-parse = shakenbreak.cli:parse
    - shakenbreak-analyse = shakenbreak.cli:analyse
    - shakenbreak-plot = shakenbreak.cli:plot
    - shakenbreak-regenerate = shakenbreak.cli:regenerate
    - shakenbreak-groundstate = shakenbreak.cli:groundstate
    - shakenbreak-mag = shakenbreak.cli:mag
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - doped >=3.2.1  # `StructureMatcher_scan_stol` required
    - pymatgen  # requirement set by doped
    - pymatgen-analysis-defects  # requirement set by doped
    - ase
    - numpy
    - click >8.0
    - hiphive >=1.0
    - importlib-metadata
    - matplotlib-base >=3.6
    - pandas >=1.1.0
    - seaborn

test:  # needs to be commented out if ever any co-dependent doped/ShakeNBreak releases
  requires:
    - python {{ python_min }}
  imports:
    - shakenbreak

  commands:
    - snb --help
    - snb-generate --help
    - snb-generate_all --help
    - snb-run --help
    - snb-parse --help
    - snb-analyse --help
    - snb-plot --help
    - snb-regenerate --help
    - snb-groundstate --help
    - snb-mag --help
    - shakenbreak --help
    - shakenbreak-generate --help
    - shakenbreak-generate_all --help
    - shakenbreak-run --help
    - shakenbreak-parse --help
    - shakenbreak-analyse --help
    - shakenbreak-plot --help
    - shakenbreak-regenerate --help
    - shakenbreak-groundstate --help
    - shakenbreak-mag --help

about:
  home: https://github.com/SMTG-Bham/ShakeNBreak
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Package to generate and analyse distorted defect structures, in order to identify ground-state and metastable defect configurations.
  doc_url: https://shakenbreak.readthedocs.io/en/latest/
  dev_url: https://github.com/SMTG-Bham/ShakeNBreak

extra:
  recipe-maintainers:
    - kavanase
    - ireaml
